name: test_backend

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test_backend:
    runs-on:  ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: run test
        run:  |
        cd backend
        go test -v ./...
